appName: 'image-similarity-search'
image:
  repo: image-similarity-search
  tag: latest
  pullPolicy: IfNotPresent
replicas: 1
port: 8000
svcPort: 8001
newrelic:
  appName: 
  licenseKey:
imageDir: "/app/uploads"
# sqliteUrl: "sqlite://" # or use memory
sqliteUrl: "sqlite:////app/db/db.sqlite"
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1024Mi
service:
  type: 'ClusterIP'
