---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.appName }}
spec:
  selector:
    app.kubernetes.io/name: {{ $.Values.appName }}
  type: {{ $.Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ $.Values.svcPort }}
      targetPort: {{ $.Values.port }}
