name: docker_build
on:
  pull_request:
    paths:
      - 'poetry.lock'
      - 'pyproject.toml'
      - 'image_search/**'
      - '.github/workflows/docker_build.yml'
      - 'Dockerfile'
      # - 'e2e/**'
      # - 'tests/**'
jobs:
    build:
      runs-on: debian-latest
      env:
          DOCKER_BUILDKIT: '1'
      steps:
          - name: checkout
            uses: actions/checkout@v2
            timeout-minutes: 2

          - name: Build Container
            uses: docker/build-push-action@v2
            with:
              context: .
              push: false
            timeout-minutes: 10

          # TODO
          # - name: Upload to GAR
