name: tests
on:
  pull_request:
    # TODO: 
    # paths:
    #   - 'poetry.lock'
    #   - 'pyproject.toml'
    #   - 'image_search/**'
    #   - '.github/workflows/tests.yml'
    #   - 'e2e/**'
    #   - 'tests/**'
    #   - 'scripts/run-*-tests.sh'
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
        DOCKER_BUILDKIT: '1'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        timeout-minutes: 2

      # TODO: speed up builds
      # - name: setup build cache
      #   uses: actions/cache@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # TODO: There's probably a good way to do much this with a single action
      - name: install poetry
        run: python3 -m pip install poetry
  
      - name: poetry install
        run: poetry install

      - name: unit tests
        run: scripts/run-unit-tests.sh

      - name: e2e tests
        run: poetry run pytest e2e
        # run: scripts/run-e2e-tests.sh # could probably delete the