name: tests
on:
  pull_request:
    # paths:
    #   - 'poetry.lock'
    #   - 'pyproject.toml'
    #   - 'image_search/**'
    #   - '.github/workflows/tests.yml'
    #   - 'e2e/**'
    #   - 'tests/**'
    #   - 'scripts/run-*-tests.sh'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_BUILDKIT: '1'
    steps:
      - name: checkout
        uses: actions/checkout@v2
        timeout-minutes: 2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: e2e tests
        run: scripts/run-e2e-tests.sh

      - name: unit tests
        run: scripts/run-unit-tests.sh
